name: Build project

run-name: Running CI by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'
      - '!*.md'
  workflow_dispatch:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .cicd/docker/Dockerfile
          target: run_tests
          build-args: |
            "SAMPCTL_GITHUB_TOKEN=${{ secrets.GH_PAT }}"
          push: false
