name: server-ci

run-name: Running server-ci by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'
      - '!*.md'
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: Run tests
        uses: docker/build-push-action@v3
        with:
          context: .
          file: .cicd/docker/Dockerfile
          target: run_tests
          build-args: |
            "SAMPCTL_GITHUB_TOKEN=${{ secrets.GH_PAT }}"
          push: false
      - name: Check if tests passed
        if: failure()
        run: |
          echo "::error title=Unit Tests Failed::Check Docker build logs for more information."
          exit 1
